### PR TITLE
Added support for Schnorr signatures

### PR DESCRIPTION
**Pull request by devos50**

### CODE REVIEW

**Comment by devos50** [comment]
Whoops, this one should have gone to my own fork instead 😁

**Comment by ofek** [comment]
Are you planning on re-opening after you've tested?

**Comment by devos50** [comment]
Yes, I can prepare a PR to this repo when I’m done with the implementation and testing 👍

**Comment by roks0n** [comment]
hi @devos50, is the schnorr implementation on your fork finished by any chance?

**Comment by devos50** [comment]
@roks0n I currently do have the bindings to the FROST code operational in [this branch](https://github.com/devos50/coincurve/tree/frost) but I haven't worked on the code for a while though. When compiling the source code, running [this script](https://github.com/devos50/coincurve/blob/frost/frost.py) should generate valid FROST signatures. 👍 

Note that our students have also worked on getting FROST signatures operational on Android. Their public progress ticket can be found [here](https://github.com/Tribler/tribler/issues/6788).

**Pull request closed without merging**
