### PR TITLE
Proposing refactoring of build process

### PR DESCRIPTION
**Pull request by MementoRC**
Final goal is to have a (hopefully) simplified build process to mitigate
   - Relying on antiquated `cffi_modules`
      . It defines `-lsecp256k1` which will fail with a CMake-based SECP256K1 build
      . It reduce the tailoring of CFFI build
   - Revamp the CFFI build process to customize the _libsecp256k1.c file compilation

Hopefully, the commits will be self-explanatory and help verify a step-by-step transition

### CODE REVIEW

**Comment by ofek** [comment]
I would be extremely interested in getting rid of CFFI and using a usual extension if possible without you having to invest a lot of your time.

**Comment by ofek** [comment]
Actually there might not be any benefit to that, forget me. Please continue doing what you were doing here before!

**Comment by MementoRC** [comment]
So in this proposal, CFFI is only used to prepare the _libsecp256k1.c interface and use the extension to build/link. One reason I am working on this is that when I tried to use the CMake to build libsecp256k1.a, it failed because they don't use -fPIC and gcc complains when building. So a more customized linking is needed, which is not possible with cffi_module
But then ... MacOS decide to join the belligerent camp :\

**Comment by MementoRC** [comment]
My worry is that too many changes will be needed, I don't know see how to make incremental commit/merge to master in this case

**Comment by ofek** [comment]
I don't care what we merge as long as it passes tests and I will verify locally on my Windows machine using one of the built artifacts.

**Comment by MementoRC** [comment]
@ofek As I was struggling with the static lib, I ventured into the dynamic lib and wondered if it would not be simpler to provide `libsecp256k1.so` as part of coincurve build. Currently, it is the same only with SECP256K1 library hidden inside _libsecp245k1.

What I mean is that it is conceptually the same thing

I will propose to add:
```
coincurve
   |
   ---> lib
           |
            ---> libsecp256k1.so/dylib/dll  (might be a bit confusing for windows)
```

**Comment by MementoRC** [comment]
> I don't care what we merge as long as it passes tests and I will verify locally on my Windows machine using one of the built artifacts.

Have you been able to reproduce the issue and verify that the current master resolved it? If so, we should probably release.

**Comment by ofek** [comment]
image

**Comment by MementoRC** [comment]
This seems to be the consequence of moving the dependencies into the `pyproject.toml`. I did that because when first tried the conda recipe, it seemed to need PEP517

I can take a look at it

**Comment by MementoRC** [comment]
@ofek https://github.com/ofek/coincurve/pull/142 seems to be resolving this issue

**Comment by MementoRC** [comment]
@ofek I continue to commit to this PR so that you can follow the updates if needed. If something requires a lot of debug, I'll switch over to my fork

**Comment by MementoRC** [comment]
Closing for debug purpose

**Comment by MementoRC** [comment]
@ofek THis is close enough for your review and suggestions. Currently, the build uses a static libsecp256k1, but it should also work (tested on my branches) with a shared lib.

When built with a shared lib, `coincurve` will package the dynamic library, so it's unclear whether you'd want to provide a wheel for that build, it could be interesting if someone runs multiple instances of coincurve, it would then benefit from the dynamic link

**Comment by MementoRC** [comment]
Windows is such ... Do you spot something that I am missing:
```
  C:\Users\runneradmin\AppData\Local\Temp\cibw-run-g9acegp8\cp312-win_amd64\venv-test\Lib\site-packages\coincurve\__init__.py:31: UserWarning: DBG: libsecp256k1:EXTTERNAL
678
    load_secp256k1_conda_library()
679
  LoadLibrary \Device\HarddiskVolume2\Windows\System32\kernel.appcore.dll
680
  LoadLibrary \Device\HarddiskVolume2\Miniconda\envs\test\Library\bin\libsecp256k1-2.dll
681
  LoadLibrary \Device\HarddiskVolume2\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.12.1\tools\DLLs\_wmi.pyd
682
  LoadLibrary \Device\HarddiskVolume2\Windows\System32\propsys.dll
683
  LoadLibrary \Device\HarddiskVolume2\Users\runneradmin\AppData\Local\Temp\cibw-run-g9acegp8\cp312-win_amd64\venv-test\Lib\site-packages\coincurve\_libsecp256k1.cp312-win_amd64.pyd
684
  LoadLibrary \Device\HarddiskVolume2\Users\runneradmin\AppData\Local\Temp\cibw-run-g9acegp8\cp312-win_amd64\venv-test\Lib\site-packages\_cffi_backend.cp312-win_amd64.pyd
685
  LoadLibrary \Device\HarddiskVolume2\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.12.1\tools\DLLs\_hashlib.pyd
686
  LoadLibrary \Device\HarddiskVolume2\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.12.1\tools\DLLs\libcrypto-3.dll
687
  LoadLibrary \Device\HarddiskVolume2\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.12.1\tools\DLLs\unicodedata.pyd
688
  LoadLibrary \Device\HarddiskVolume2\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.12.1\tools\DLLs\_socket.pyd
689
  LoadLibrary \Device\HarddiskVolume2\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.12.1\tools\DLLs\select.pyd
690
  LoadLibrary \Device\HarddiskVolume2\Users\runneradmin\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\python.3.12.1\tools\DLLs\_decimal.pyd
691
  C:\Users\runneradmin\AppData\Local\Temp\cibw-run-g9acegp8\cp312-win_amd64\venv-test\Lib\site-packages\coincurve\__init__.py:31: UserWarning: DBG: libsecp256k1:EXTTERNAL
692
    load_secp256k1_conda_library()
693
  Traceback (most recent call last):
694
    File "<string>", line 1, in <module>
695
    File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-g9acegp8\cp312-win_amd64\venv-test\Lib\site-packages\coincurve\__init__.py", line 33, in <module>
696
      from coincurve.context import GLOBAL_CONTEXT, Context  # noqa: E402
697
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
698
    File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-g9acegp8\cp312-win_amd64\venv-test\Lib\site-packages\coincurve\context.py", line 5, in <module>
699
      from coincurve._libsecp256k1 import ffi, lib
700
  ImportError: DLL load failed while importing _libsecp256k1: The specified module could not be found.
701
```

**Comment by ofek** [comment]
I'm not sure honestly

**Comment by MementoRC** [comment]
Thanks, case of too much desperation. In this case the issue was EXTTERNAL typo. Well, not only I don't like windows (so very biased), but I am frustrated with how often I mistype or write something silly

The good news is: It is finally working ... well, at least until I find that I actually didn't do it right ... but for a start of the weekend, I'll blissfully take it

Ok, now for the tough question ... how do we do this? There are lots of changes

**Comment by ofek** [comment]
First I would rebase to resolve conflicts and then get CI passing.

**Comment by MementoRC** [comment]
Oh no, I will close this PR (I thought I had done so already, absent-minded) - You said you did not want to change the download, which this PR included

I was referring to the significant changes in the flow that I finally completed (I will make a new PR, to hide all the shameful craziness I went through)

**Pull request closed without merging**
