### PR TITLE
(feat) wrapper to subprocess calls?

### PR DESCRIPTION
**Pull request by MementoRC**
A lot of times I forgot to put the `noqa`, thus I had created this wrapper. It also helped me browse through the logs and debug specific calls.

### CODE REVIEW

**Comment by MementoRC** [comment]
There may be smarter ways to do this, it just makes the debugging a tidbit easier

**Comment by ofek** [comment]
I see commented out code blocks; is this ready for review?

**Comment by MementoRC** [comment]
Right, these are 2 functions that do not seem to be used. I wasn't thinking straight, you would still see them in the review if I had removed them

**Comment by MementoRC** [comment]
@ofek Ready for review - I'll refrain from updating it

**Review by ofek — APPROVED** [review]

**Pull request merged**
