### PR TITLE
Remove SECP256K1 deprecated context flags

### PR DESCRIPTION
**Pull request by MementoRC**
Proposal to remove the deprecated CONTEXT flags

Source SECP256K1 include/secp256k1.h:
https://github.com/bitcoin-core/secp256k1/blob/e4af41c61b0bb55fc9614cb39df8e455715b4dd4/include/secp256k1.h#L207

### CODE REVIEW

**Comment by ofek** [comment]
What was the issue?

**Comment by MementoRC** [comment]
@ofek The `#define xxx (value | value)` may not be interpreted by CFFI. Looking at older version I see that you had already hardcoded the integer value in `_windows_libsecp256k1.py`
Well, I have not been able to confirm that it is the issue

**Comment by carterbox** [comment]
IMHO, these changes seem too extensive. The conda package which uses an external dynamically linked libsecp256k1 instead of a revended statically linked libsecp256k1 is able to be imported on Windows. That means the problem with the PYPI package (the difference between the PYPI and conda package) should be related to building and linking libsecp256k1 only.

**Comment by MementoRC** [comment]
There are several changes that are related but not necessary. I think the key issue was in the `_windows_libsecp256k1.py`, which is used in the PyPI build process and not in the conda build. I actually wonder if it is needed, perhaps it was needed only for previous version of CFFI 

How to check that this will solve the issue? - My way was to implement a windows-wheel build/test, but it requires a lot of try/error, I don't mind going through it, but if a simpler way is available, it would be great

**Comment by MementoRC** [comment]
This PR is a bit too messy. Resubmitting in a more orderly fashion

**Pull request closed without merging**
