### PR TITLE
BIP340 x-only keys and Schnorr signatures

### LINKED ISSUE #114: x-only (BIP340) public keys support
It would be useful for coincurve to upgrade to latest secp256k1 and get support for x-only public keys (along with tweaking etc) for usage with Taproot.

I'm looking into working on this but i'm not familiar with the internals of the library, and it looks like the change would be a bit invasive since a lot of the existing APIs would have to be noted to only work with non-BIP340 public keys.

Have you looked into it? Is an upgrade of libsecp planned soon?
Thanks!

### PR DESCRIPTION
**Pull request by darosior**
Based on #115 this adds support for [BIP340](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki) x-only keys.

This allows users to access libsecp256k1's utilities around Schnorr signatures and the Taproot tweak.

Closes #114.

### CODE REVIEW

**Comment by darosior** [comment]
Rebased on #115 and added Schnorr signatures support. This is now ready for review.

**Comment by darosior** [comment]
I'm not sure where this wheels building issue could be coming from. @ofek do you have any idea or suggestion for fixing this?

**Comment by darosior** [comment]
I need to add a test for the parity bit, too.

**Comment by darosior** [comment]
Alright, i've fixed the issue with the wheels build (that was hiding a memory bug in the management of the `int` passed by reference to get the parity of the key). This is now passing CI.

I've added more tests to cover the `__eq__`, `tweak_add` and `parity` that weren't previously covered. This is now ready for review.

**Comment by kigawas** [comment]
Looks good. 
Perhaps you may add more tests for `ValueError` to fix the coverage warning.

**Comment by darosior** [comment]
Happy to review a follow-up PR that does that. This patch already has 88% coverage and is increasing the overall project's coverage (according to Codecov).

@ofek anything else you'd like me to do here before merging this?

**Review by ofek — APPROVED** [review]
Thanks!!!

**Comment by ofek** [comment]
https://pypi.org/project/coincurve/18.0.0/

**Comment by darosior** [comment]
Thanks! :heart:

**Pull request merged**
